### ISSUE TITLE
Patterns of Enterprise Application Architecture

### ISSUE THREAD

**Issue by lavoiee** [andreagrandi/covid-api#17]
I just downloaded your source code and started reading through it. I have a limited experience in software development and I'm still learning. I'm familiar with the MVC pattern but it doesn't appear that this is the pattern you used. Could you please provide a link to some information that described the design pattern you used or that is used in the industry when developing an API such as this?

Thanks in advance
Eric

**Comment by andreagrandi** [comment]
Hi, I'm afraid but we haven't used any "standard" structure or anything. We have just built from examples available in FastAPI documentation and other examples found online. The structure is quite simple but if you have any specific question, please feel free to ask.

**Comment by MatMoore** [comment]
Hi @lavoiee, I would recommend reading through the FastAPI tutorial to start with: https://fastapi.tiangolo.com/tutorial/

I would say it's still following a kind of MVC structure but the main difference from MVC web frameworks you may be familiar with is that instead of templated views we have "schemas" which are classes that inherit from `pydantic.BaseModel`. These get automagically mapped to the JSON the API returns.

If you are looking to understand the existing code, maybe try starting from `api.views`, as that's where it decides what code to execute based on the URL.

There is also some discussion in https://github.com/andreagrandi/covid-api/issues/5 about the changes we've made to the structure beyond that.

**Comment by lavoiee** [comment]
@MatMoore @andreagrandi Thank you for the suggestions. I appreciate it.
