### ISSUE TITLE
Which database should we use?

### ISSUE THREAD

**Issue by andreagrandi** [andreagrandi/covid-api#2]
We need a DB to begin with.

Is something like [TinyDB](https://tinydb.readthedocs.io) enough? Should we use PostgreSQL?

**Comment by audreyfeldroy** [comment]
It's all public data, right? Nothing private that we're going to store?

**Comment by andreagrandi** [comment]
<img width="942" alt="Screenshot 2020-02-29 19 00 33" src="https://user-images.githubusercontent.com/636391/75612636-c679a580-5b25-11ea-8239-2f73b9223159.png">

It should be all public data as far as I know. There are only the numbers of: confirmed infections, deaths and recoveries. Other data are about the **date** and the **country**

**Comment by audreyfeldroy** [comment]
I'm good with TinyDB - keep things simple, right?

**Comment by andreagrandi** [comment]
> I'm good with TinyDB - keep things simple, right?

I'm having second thoughs on it. I will need to carefully ready the docs, but my initial understanding is that it's not meant to be used by multiple people at the same time (just like the "old" Sqlite).

The db itself points to just a "file": `db = TinyDB('path/to/db.json')`
and this will make it even harder to deploy.

If we want to keep things simple at the beginning, we could do something like this:

we pick a technology that can essentially be used anywhere and we start with something simple like **Heroku** free layer (using either FastAPI/Django + PostgreSQL), allowing access to the API as "invitation only" or setting up a very aggressive cache policy (we update the data daily so it should be fine), so we don't have to waste time on a complex deployment at the beginning.

Please let me know what do you think about.

**Comment by MatMoore** [comment]
👍  for heroku. It's great for prototyping, and since the responses are very cacheable maybe we could stick a CDN in front to improve availablity.

I've never used TinyDB, but it sounds like we could get away with it if the production app will only read from the database. In that case we could bundle the db.json file with the files we deploy and then each instance of the server would read its own copy. 

Postgres does seem easier though, it will definitely just work with heroku and SQLAlchemy, and it will perform well. If we're going to use SQLAlchemy anyway, then we're not benefiting from the "clean API" of TinyDB. Postgres can also do document-oriented stuff using json fields, so we don't have to define all the schema up front if we just want to prototype something quickly.

Postgres is pretty easy to install on a dev machine, or you can run it in docker. However, the heroku free tier does come with [some limits](https://elements.heroku.com/addons/heroku-postgresql), for example, there is a row limit of 10,000.

**Comment by fundor333** [comment]
In the TinyDB docs you find the [Why Not Use TinyDB?](https://tinydb.readthedocs.io/en/latest/intro.html#why-not-use-tinydb) with the "access from multiple processes or threads" as first point. 

For starting or other type of project maybe it is a good choice but if the server grow you need to refactory out TinyDB for another db

**Comment by andreagrandi** [comment]
All right. Let's stick with Sqlite and/or PostgreSQL for local development and PostgreSQL for production. It should be quite easy to switch between the two and unless we use something which is only compatible with PostgreSQL, we should be able to switch just changing the connection string.
